'use client';
import {useEffect,useState} from 'react';
import {Pencil,Trash2} from 'lucide-react';
import type {IUMoment,IUKind} from './iu-types';
export default function IUMomentEditor({kind,moments,addSignal,onChanged}:{kind:IUKind,moments:IUMoment[],addSignal:number,onChanged:()=>Promise<void>}){
 const [editing,setEditing]=useState<Partial<IUMoment>|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const sections=[...new Set(moments.filter(m=>m.kind==='simulator').map(m=>m.section))];
 useEffect(()=>{if(addSignal)setEditing({kind,section:kind==='op'?'op':sections[0]||'Nya moment',title:'',description:'',maxScore:1})},[addSignal]);
 useEffect(()=>{setEditing(null);setMessage('')},[kind]);
 function open(moment:IUMoment){setEditing({...moment});setMessage('')}
 async function request(method:string,body:unknown){const res=await fetch('/api/personnel/moments',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await res.json();if(!res.ok)throw Error(value.error||'Ett fel uppstod')}
 async function save(e:React.FormEvent){e.preventDefault();if(!editing)return;setBusy(true);try{await request(editing.id?'PUT':'POST',editing);await onChanged();setEditing(null);setMessage('IU-momentet är sparat.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function remove(moment:IUMoment){if(!window.confirm(`Ta bort ”${moment.title}” från nya uppföljningar? Tidigare sparade protokoll behåller momentet.`))return;setBusy(true);try{await request('DELETE',{id:moment.id});await onChanged();setMessage('IU-momentet har tagits bort från nya uppföljningar.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <><div className="studentlist iumomentlist">{moments.filter(m=>m.kind===kind).map(moment=><div className="student" key={moment.id}><span><strong>{moment.title}</strong><small>{moment.kind==='op'?(moment.section==='chef'?'Ämnen till chef':'Bedömningsområden'):moment.section+' · '+moment.maxScore+' maxpoäng'}</small>{moment.description&&<small>{moment.description.slice(0,140)}</small>}</span><div className="momentactions"><button className="editicon" onClick={()=>open(moment)} aria-label={'Redigera '+moment.title}><Pencil size={17}/></button><button className="editicon deleteicon" disabled={busy} onClick={()=>remove(moment)} aria-label={'Ta bort '+moment.title}><Trash2 size={17}/></button></div></div>)}{!moments.some(m=>m.kind===kind)&&<div className="empty">Inga IU-moment ännu. Lägg till det första momentet.</div>}</div>{message&&<p className="personnelnotice" role="status">{message}</p>}{editing&&<div className="modalback" onClick={()=>setEditing(null)}><form className="modal momentmodal" onClick={e=>e.stopPropagation()} onSubmit={save}><h2>{editing.id?'Redigera IU-moment':'Nytt IU-moment'}</h2><label>Rubrik<input required autoFocus maxLength={180} value={editing.title||''} onChange={e=>setEditing({...editing,title:e.target.value})}/></label>{kind==='op'?<label>Område<select value={editing.section} onChange={e=>setEditing({...editing,section:e.target.value})}><option value="op">Bedömningsområden</option><option value="chef">Ämnen till chef</option></select></label>:<><label>Momentgrupp<input required list="iu-simulator-sections" maxLength={180} value={editing.section||''} onChange={e=>setEditing({...editing,section:e.target.value})}/><datalist id="iu-simulator-sections">{sections.map(section=><option key={section} value={section}/>)}</datalist></label><label>Maxpoäng<input type="number" required min={0} max={1000} value={editing.maxScore??0} onChange={e=>setEditing({...editing,maxScore:Number(e.target.value)})}/></label></>}<label>Beskrivning<textarea rows={8} maxLength={10000} value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><div className="modalactions"><button type="button" onClick={()=>setEditing(null)}>Avbryt</button><button className="primary" disabled={busy}>Spara moment</button></div></form></div>}</>;
}
