'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,Pencil,Trash2,ArrowUp,ArrowDown} from 'lucide-react';
import type {IUMoment,IUKind,IUOperationalCategory} from './iu-types';
export default function IUMomentEditor({kind,moments,categories,addSignal,onChanged}:{kind:IUKind,moments:IUMoment[],categories:IUOperationalCategory[],addSignal:number,onChanged:()=>Promise<void>}){
 const [editing,setEditing]=useState<Partial<IUMoment>|null>(null),[categoryForm,setCategoryForm]=useState<{id?:string,title:string}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const lastAdd=useRef(addSignal);
 function newMoment(categoryId:string|null=null){setEditing({kind,section:'op',operationalCategoryId:categoryId,title:'',description:'',maxScore:null});setMessage('')}
 useEffect(()=>{if(lastAdd.current===addSignal)return;lastAdd.current=addSignal;if(addSignal)newMoment(categories[0]?.id||null)},[addSignal]);
 useEffect(()=>{setEditing(null);setCategoryForm(null);setMessage('')},[kind]);
 async function request(url:string,method:string,body:unknown){const res=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await res.json();if(!res.ok)throw Error(value.error||'Ett fel uppstod')}
 async function save(e:React.FormEvent){e.preventDefault();if(!editing)return;setBusy(true);try{await request('/api/personnel/moments',editing.id?'PUT':'POST',editing);await onChanged();setEditing(null);setMessage('IU-momentet är sparat.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function remove(moment:IUMoment){if(!window.confirm(`Ta bort ”${moment.title}” från nya uppföljningar? Tidigare sparade protokoll behåller momentet.`))return;setBusy(true);try{await request('/api/personnel/moments','DELETE',{id:moment.id});await onChanged();setMessage('IU-momentet har tagits bort från nya uppföljningar.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function saveCategory(e:React.FormEvent){e.preventDefault();if(!categoryForm)return;setBusy(true);try{await request('/api/personnel/operational-categories',categoryForm.id?'PUT':'POST',categoryForm);await onChanged();setCategoryForm(null);setMessage('Kategorin är sparad.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function removeCategory(category:IUOperationalCategory){if(!window.confirm(`Ta bort kategorin ”${category.title}”? Momenten behålls under Utan kategori. Tidigare sparade protokoll påverkas inte.`))return;setBusy(true);try{await request('/api/personnel/operational-categories','DELETE',{id:category.id});await onChanged();setMessage('Kategorin är borttagen. Momenten finns kvar under Utan kategori.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function moveCategory(category:IUOperationalCategory,direction:'up'|'down'){setBusy(true);try{await request('/api/personnel/operational-categories','PATCH',{id:category.id,direction});await onChanged();setMessage('Kategoriernas ordning är sparad.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 const operative=moments.filter(moment=>moment.kind===kind),known=new Set(categories.map(category=>category.id));
 const groups=[...categories.map(category=>({...category,rows:operative.filter(moment=>moment.operationalCategoryId===category.id)})),{id:'uncategorized',title:'Utan kategori',position:0,rows:operative.filter(moment=>!moment.operationalCategoryId||!known.has(moment.operationalCategoryId))}].filter(group=>group.id!=='uncategorized'||group.rows.length||!categories.length);
 return <>
 <div className="iucategorytoolbar"><button type="button" className="secondary" disabled={busy} onClick={()=>{setMessage('');setCategoryForm({title:''})}}><Plus size={17}/> Ny kategori</button></div>
 {groups.map(group=><section className="iucategorygroup" key={group.id}><div className="iucategoryhead"><h3>{group.title}</h3><span>{group.rows.length} moment</span>{group.id!=='uncategorized'&&<div className="momentactions categoryorderactions"><button type="button" className="editicon" disabled={busy||categories[0]?.id===group.id} onClick={()=>moveCategory(group,'up')} aria-label={'Flytta kategori '+group.title+' upp'} title="Flytta upp"><ArrowUp size={16}/></button><button type="button" className="editicon" disabled={busy||categories[categories.length-1]?.id===group.id} onClick={()=>moveCategory(group,'down')} aria-label={'Flytta kategori '+group.title+' ned'} title="Flytta ned"><ArrowDown size={16}/></button><button type="button" className="editicon" disabled={busy} onClick={()=>{setMessage('');setCategoryForm({id:group.id,title:group.title})}} aria-label={'Redigera kategori '+group.title}><Pencil size={16}/></button><button type="button" className="editicon deleteicon" disabled={busy} onClick={()=>removeCategory(group)} aria-label={'Ta bort kategori '+group.title}><Trash2 size={16}/></button></div>}</div>
 <div className="studentlist iumomentlist">{group.rows.map(moment=><div className="student" key={moment.id}><span><strong>{moment.title}</strong>{moment.description&&<small>{moment.description.slice(0,140)}</small>}</span><div className="momentactions"><button type="button" className="editicon" disabled={busy} onClick={()=>{setEditing({...moment});setMessage('')}} aria-label={'Redigera '+moment.title}><Pencil size={17}/></button><button type="button" className="editicon deleteicon" disabled={busy} onClick={()=>remove(moment)} aria-label={'Ta bort '+moment.title}><Trash2 size={17}/></button></div></div>)}{!group.rows.length&&<div className="empty">Inga moment i kategorin ännu.</div>}</div>
 <div className="iucategoryadd"><button type="button" className="textaction" disabled={busy} onClick={()=>newMoment(group.id==='uncategorized'?null:group.id)}><Plus size={16}/> Lägg till moment</button></div></section>)}
 {message&&<p className="personnelnotice" role="status">{message}</p>}
 {editing&&<div className="modalback" onClick={()=>{if(!busy)setEditing(null)}}><form role="dialog" aria-modal="true" aria-labelledby="iu-moment-title" className="modal momentmodal" onClick={e=>e.stopPropagation()} onSubmit={save}><h2 id="iu-moment-title">{editing.id?'Redigera IU-moment':'Nytt IU-moment'}</h2><label>Rubrik<input required autoFocus maxLength={180} value={editing.title||''} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Kategori<select value={editing.operationalCategoryId||''} onChange={e=>setEditing({...editing,operationalCategoryId:e.target.value||null})}><option value="">Utan kategori</option>{categories.map(category=><option key={category.id} value={category.id}>{category.title}</option>)}</select></label><label>Beskrivning<textarea rows={8} maxLength={10000} value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><div className="modalactions"><button type="button" disabled={busy} onClick={()=>setEditing(null)}>Avbryt</button><button className="primary" disabled={busy}>Spara moment</button></div>{message&&<p role="alert">{message}</p>}</form></div>}
 {categoryForm&&<div className="modalback" onClick={()=>{if(!busy)setCategoryForm(null)}}><form className="modal" role="dialog" aria-modal="true" aria-labelledby="iu-category-title" onClick={e=>e.stopPropagation()} onSubmit={saveCategory}><h2 id="iu-category-title">{categoryForm.id?'Redigera kategori':'Ny kategori'}</h2><label>Kategorinamn<input autoFocus required maxLength={180} value={categoryForm.title} onChange={e=>setCategoryForm({...categoryForm,title:e.target.value})}/></label><div className="modalactions"><button type="button" disabled={busy} onClick={()=>setCategoryForm(null)}>Avbryt</button><button className="primary" disabled={busy}>Spara kategori</button></div>{message&&<p role="alert">{message}</p>}</form></div>}
 </>;
}
