import { db,removePerson,renamePerson } from '../../database';
import { currentUser,error } from '../../auth';
import {stockholmYear} from '../../followup-status';
export const dynamic='force-dynamic';
const permitted=(role:string)=>role==='Administratör'||role==='Instruktör';
export async function GET(){try{
 const u=await currentUser();if(!u||!permitted(u.role))return error('Behörighet saknas',403);const year=stockholmYear();
 const {results}=await db.prepare("SELECT p.id,p.name,p.created_at AS createdAt,COUNT(DISTINCT f.kind) FILTER (WHERE f.outcome='approved')=2 AS completed,MAX(f.outcome) FILTER (WHERE f.kind='op') AS opOutcome,MAX(f.outcome) FILTER (WHERE f.kind='simulator') AS simulatorOutcome FROM personnel p LEFT JOIN LATERAL (SELECT kind,CASE WHEN followup_date LIKE ? OR outcome='requires_completion' THEN outcome ELSE NULL END AS outcome FROM (SELECT DISTINCT ON (kind) kind,outcome,followup_date FROM personnel_followups WHERE personnel_id=p.id ORDER BY kind,followup_date DESC,created_at DESC,id DESC) latest) f ON true WHERE p.moved_at IS NULL GROUP BY p.id,p.name,p.created_at ORDER BY p.name COLLATE NOCASE").bind(year+'-%').all();
 const {results:drafts}=await db.prepare('SELECT personnel_id AS personId,kind,draft_year AS year FROM personnel_followup_drafts WHERE form IS NOT NULL').all<{personId:string,kind:string,year:string}>();
 return Response.json(results.map(person=>({...person,statusYear:year,opDraftYear:drafts.find(d=>d.personId===person.id&&d.kind==='op')?.year,simulatorDraftYear:drafts.find(d=>d.personId===person.id&&d.kind==='simulator')?.year}))); 
 }catch{return error('Kunde inte läsa personal',503)}}
export async function POST(req:Request){try{const u=await currentUser();if(!u||!permitted(u.role))return error('Behörighet saknas',403);const {name}=await req.json();if(typeof name!=='string'||!name.trim()||name.length>120)return error('Ange namn',400);const id=crypto.randomUUID(),now=Date.now();await db.prepare('INSERT INTO personnel(id,name,created_at,created_by) VALUES(?,?,?,?)').bind(id,name.trim(),now,u.email).run();return Response.json({id,name:name.trim(),createdAt:now})}catch{return error('Kunde inte spara personal',503)}}
export async function PUT(req:Request){try{const u=await currentUser();if(!u||!permitted(u.role))return error('Behörighet saknas',403);const {id,name}=await req.json() as {id:unknown,name:unknown};if(typeof id!=='string'||!id||typeof name!=='string'||!name.trim()||name.length>120)return error('Ogiltigt namn',400);if(!await renamePerson(id,'personnel',name.trim()))return error('Personen finns inte',404);return Response.json({id,name:name.trim()})}catch{return error('Kunde inte ändra namnet',503)}}
export async function DELETE(req:Request){try{const u=await currentUser();if(!u||!permitted(u.role))return error('Behörighet saknas',403);const {id}=await req.json();if(typeof id!=='string'||!id)return error('Personal saknas',400);if(!await removePerson(id,'personnel'))return error('Personal finns inte',404);return Response.json({ok:true})}catch{return error('Kunde inte ta bort personal',503)}}
